# This is a basic workflow that is manually triggered

name: Release
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      niko_hash:
        description: "Niko Version"
        required: true
        default: "none"
      robin_hash:
        description: "Robin Version"
        required: true
        default: "none"
      plandata_hash:
        description: "PlanData + Niko"
        required: true
        default: "none"



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send Robin
      run: echo "Robin Version: ${{ github.event.robin_hash.name }}"
    - name: Send Niko
      run: echo "Niko Version: ${{ github.event.niko_hash.name }}"
    - name: Send PlanData
      run: echo "PlanData Version: ${{ github.event.plandata_hash.name }}"
